# Site settings
name: Mind behind Mind
email: leeskyed@gmail.com
author: Leesky
url: http://leeskyed.github.io
github: https://github.com/leeskyed
baseurl: ""
description: ""
meta_description: Li Shikai; Shenzhen University; The End of the World; Valued;
motto: 珍重;
banner: Dream big, think small.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: leeskyed

# Build settings
markdown: kramdown

baidu_analysis: f86a32148abf29b9e115e37abfb75eb8

